events {
    worker_connections 256; 
}

http {
    server {
        listen 80;
        
        # --- PODATNOŚCI NA ATAKI LOW-RATE ---
        
        # Podatność na RUDY: Czekamy bardzo długo na ciało zapytania POST (np. 1 bajt co 10s)
        client_body_timeout 300s;
        
        # Podatność na Slowloris: Czekamy bardzo długo na dokończenie nagłówków HTTP
        client_header_timeout 300s;
        
        # Podtrzymujemy otwarte połączenia przez długi czas
        keepalive_timeout 300s;
        
        # --- KONIEC PODATNOŚCI ---

        location / {
            proxy_pass http://backend_app:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}